name: Sync Secrets to Vercel
description: Sync Repository Secrets to Vercel Environment
author: Akhmad Thoriq
inputs:
  prefix:
    description: Prefix for the secrets to sync
    required: false
    default: ENV_
  environments:
    description: The name of the Vercel Environment. If multiple, separate with comma
    required: false
    default: production
  project:
    description: The name of the Vercel Project.
    required: true
  team_id:
    description: The ID of the Vercel Team.
    required: true
  token:
    description: The Vercel Token.
    required: true
  secrets:
    description: The GitHub secrets encoded in JSON format
    required: true
  cancel_on_fail:
    description: Cancel the workflow if one of the secrets failed to sync
    required: false
    default: true

runs:
  using: node20
  main: dist/index.js
branding:
  icon: tag
  color: blue
